// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BoZG5l7ExowEHSd3Yf1JvGi_VQQIok4',
    appId: '1:1018669852108:web:93a7eae31cf96208a22969',
    messagingSenderId: '1018669852108',
    projectId: 'mxplayer-c9e84',
    authDomain: 'mxplayer-c9e84.firebaseapp.com',
    storageBucket: 'mxplayer-c9e84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1NJzmg5-Lxm7xoVfp_ygPUYcV69yZ-0',
    appId: '1:1018669852108:android:9667f50299609d25a22969',
    messagingSenderId: '1018669852108',
    projectId: 'mxplayer-c9e84',
    storageBucket: 'mxplayer-c9e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFi6VbaGX8UqnQ6Yz0ayU7wFwQXAq4B5c',
    appId: '1:1018669852108:ios:d815c99efa1ff90ea22969',
    messagingSenderId: '1018669852108',
    projectId: 'mxplayer-c9e84',
    storageBucket: 'mxplayer-c9e84.appspot.com',
    iosBundleId: 'com.example.mxPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFi6VbaGX8UqnQ6Yz0ayU7wFwQXAq4B5c',
    appId: '1:1018669852108:ios:d815c99efa1ff90ea22969',
    messagingSenderId: '1018669852108',
    projectId: 'mxplayer-c9e84',
    storageBucket: 'mxplayer-c9e84.appspot.com',
    iosBundleId: 'com.example.mxPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_BoZG5l7ExowEHSd3Yf1JvGi_VQQIok4',
    appId: '1:1018669852108:web:d429526e9ccad7a9a22969',
    messagingSenderId: '1018669852108',
    projectId: 'mxplayer-c9e84',
    authDomain: 'mxplayer-c9e84.firebaseapp.com',
    storageBucket: 'mxplayer-c9e84.appspot.com',
  );
}
